name: Python package

on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run smoke tests (only ./tests)
        run: |
          pytest -q tests
